ICU-20214 Fix cross build for Mingw-w64
It failed with a compiler error:

    i18n/unicode/numberrangeformatter.h:189:33: error:
      explicit instantiation of
      ‘struct std::atomic<icu_63::number::impl::NumberRangeFormatterImpl*>’
      in namespace ‘icu_63::number’
      (which does not enclose namespace ‘std’) [-fpermissive]

Signed-off-by: Stefan Weil <sw@weilnetz.de>