ICU-10272 the clang workaround was only *mostly* harmless. Disable it under Windows.    Fix: typeinfo(82): error C2874: using-declaration causes a multiple declaration of 'type_info'
X-SVN-Rev: 35375