the clang workaround was only *mostly* harmless. Disable it under Windows.    Fix: typeinfo(82): error C2874: using-declaration causes a multiple declaration of 'type_info'
X-Trac-URL: https://ssl.icu-project.org/trac/ticket/10272



git-svn-id: http://source.icu-project.org/repos/icu/icu/trunk@35375 0a8b766c-62c9-45f9-954d-7f2943c9ead0