[ICU-11424] Bugfix: RemoveTransliterator can cause NoClassDefFoundError
Make RemoveTransliterator._ID final, to ensure that the compiler
inlines it, so that it won't be null when register() accesses it.
X-Commit-URL: https://ssl.icu-project.org/trac/changeset/36862
Former-commit-id: a1453dc2dfb29857ad4750796508cb4980d76ca0