ICU-11424 Bugfix: RemoveTransliterator can cause NoClassDefFoundError
Make RemoveTransliterator._ID final, to ensure that the compiler
inlines it, so that it won't be null when register() accesses it.

X-SVN-Rev: 36862